// =====================================================
// ITR-V PROCESSING MODEL
// Tracks ITR-V generation, processing, and verification status
// =====================================================

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');
const enterpriseLogger = require('../utils/logger');

const ITRVProcessing = sequelize.define('ITRVProcessing', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  filingId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'filing_id',
    references: {
      model: 'itr_filings',
      key: 'id',
    },
    comment: 'Reference to ITR filing',
  },
  ackNumber: {
    type: DataTypes.STRING,
    allowNull: false,
    field: 'ack_number',
    comment: 'Acknowledgement number from ITD',
  },
  status: {
    type: DataTypes.ENUM('pending', 'generated', 'processing', 'delivered', 'verified', 'expired', 'failed'),
    allowNull: false,
    defaultValue: 'pending',
    field: 'status',
    comment: 'Current ITR-V processing status',
  },
  generatedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'generated_at',
    comment: 'When ITR-V was generated by ITD',
  },
  deliveredAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'delivered_at',
    comment: 'When ITR-V was delivered (email/post)',
  },
  verifiedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'verified_at',
    comment: 'When ITR-V was verified',
  },
  expiryDate: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'expiry_date',
    comment: 'ITR-V expiry date (120 days from generation)',
  },
  deliveryMethod: {
    type: DataTypes.ENUM('email', 'post', 'download'),
    allowNull: true,
    field: 'delivery_method',
    comment: 'How ITR-V was delivered',
  },
  documentUrl: {
    type: DataTypes.TEXT,
    allowNull: true,
    field: 'document_url',
    comment: 'URL to download ITR-V document',
  },
  verificationMethod: {
    type: DataTypes.ENUM('AADHAAR_OTP', 'NETBANKING', 'DSC', 'EVC', 'MANUAL'),
    allowNull: true,
    field: 'verification_method',
    comment: 'Method used for verification',
  },
  timeline: {
    type: DataTypes.JSONB,
    allowNull: true,
    defaultValue: [],
    field: 'timeline',
    comment: 'Array of status change events (JSON)',
  },
  metadata: {
    type: DataTypes.JSONB,
    allowNull: true,
    defaultValue: {},
    field: 'metadata',
    comment: 'Additional metadata (delivery address, tracking number, etc.)',
  },
  lastCheckedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'last_checked_at',
    comment: 'Last time status was checked from ITD portal',
  },
  createdAt: {
    type: DataTypes.DATE,
    allowNull: false,
    field: 'created_at',
  },
  updatedAt: {
    type: DataTypes.DATE,
    allowNull: false,
    field: 'updated_at',
  },
}, {
  tableName: 'itr_v_processing',
  timestamps: true,
  underscored: true,
  indexes: [
    {
      fields: ['filing_id'],
      unique: true,
      name: 'unique_itrv_per_filing',
    },
    {
      fields: ['ack_number'],
    },
    {
      fields: ['status'],
    },
    {
      fields: ['expiry_date'],
    },
    {
      fields: ['created_at'],
    },
  ],
});

module.exports = ITRVProcessing;

