// =====================================================
// ITR JSON EXPORT SERVICE
// Generates government-compliant JSON for ITR filing
// Essential for manual filing while ERI API license is pending
// =====================================================

import { authService } from './';

class ITRJsonExportService {
  constructor() {
    this.apiEndpoint = '/api/itr/export';
  }

  /**
   * Export ITR data as government-compliant JSON
   * @param {Object} itrData - Complete ITR form data
   * @param {string} itrType - Type of ITR (ITR-1, ITR-2, etc.)
   * @param {string} assessmentYear - Assessment year (e.g., '2024-25')
   * @returns {Promise<Object>} Export result with download URL
   */
  async exportToJson(itrData, itrType, assessmentYear = '2024-25') {
    try {
      // Get current user info for filing
      const user = await authService.getCurrentUser();
      if (!user) {
        throw new Error('User must be logged in to export ITR data');
      }

      // Generate government-compliant JSON structure
      const jsonPayload = this.generateGovernmentJson(itrData, itrType, assessmentYear, user);

      // Call backend to generate downloadable JSON
      const response = await fetch(this.apiEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${authService.getToken()}`
        },
        body: JSON.stringify({
          itrData: jsonPayload,
          itrType,
          assessmentYear,
          userId: user.id,
          exportFormat: 'JSON',
          purpose: 'FILING'
        })
      });

      if (!response.ok) {
        throw new Error(`Export failed: ${response.statusText}`);
      }

      const result = await response.json();

      // Generate client-side JSON as backup
      const clientJson = this.generateClientJson(itrData, itrType, assessmentYear, user);

      return {
        success: true,
        downloadUrl: result.downloadUrl,
        jsonPayload: clientJson,
        fileName: this.generateFileName(itrType, assessmentYear),
        metadata: {
          itrType,
          assessmentYear,
          generatedAt: new Date().toISOString(),
          fileSize: JSON.stringify(clientJson).length,
          checksum: this.generateChecksum(clientJson)
        }
      };

    } catch (error) {
      console.error('ITR JSON Export Error:', error);
      throw new Error(`Failed to export ITR data: ${error.message}`);
    }
  }

  /**
   * Generate government-compliant JSON structure
   * Follows Income Tax Department schema requirements
   */
  generateGovernmentJson(itrData, itrType, assessmentYear, user) {
    const currentDate = new Date().toISOString();

    // Base structure for all ITR types
    const baseJson = {
      // Header information
      'ITR_Form': itrType,
      'Assessment_Year': assessmentYear,
      'Filing_Type': 'Original',
      'Date_of_Filing': currentDate.split('T')[0], // YYYY-MM-DD format
      'Acknowledgement_Number': '', // To be generated by tax department

      // Taxpayer information
      'Taxpayer_Information': {
        'PAN': itrData.personal?.pan || user.pan || '',
        'Name': {
          'First_Name': itrData.personal?.firstName || user.firstName || '',
          'Middle_Name': itrData.personal?.middleName || '',
          'Last_Name': itrData.personal?.lastName || user.lastName || ''
        },
        'Date_of_Birth': itrData.personal?.dateOfBirth || user.dateOfBirth || '',
        'Gender': itrData.personal?.gender || user.gender || '',
        'Residential_Status': itrData.personal?.residentialStatus || 'RESIDENT',
        'Contact_Information': {
          'Email_ID': itrData.personal?.email || user.email || '',
          'Mobile_Number': itrData.personal?.phone || user.phone || '',
          'Address': {
            'Flat_Door_Block_No': itrData.personal?.address?.flat || '',
            'Premises_Name_Building': itrData.personal?.address?.building || '',
            'Road_Street': itrData.personal?.address?.street || '',
            'Area_Locality': itrData.personal?.address?.area || '',
            'City_Town': itrData.personal?.address?.city || '',
            'State': itrData.personal?.address?.state || '',
            'PIN_Code': itrData.personal?.address?.pincode || '',
            'Country': itrData.personal?.address?.country || 'INDIA'
          }
        }
      },

      // Bank account details
      'Bank_Account_Details': {
        'Account_Number': itrData.bank?.accountNumber || '',
        'Account_Type': itrData.bank?.accountType || 'SAVINGS',
        'Bank_Name': itrData.bank?.bankName || '',
        'Branch_Name': itrData.bank?.branchName || '',
        'IFSC_Code': itrData.bank?.ifscCode || '',
        'MICR_Code': itrData.bank?.micrCode || ''
      },

      // Income details
      'Income_Details': {
        'Income_from_Salary': this.formatAmount(itrData.income?.salaryIncome || 0),
        'Income_from_House_Property': this.formatAmount(itrData.income?.housePropertyIncome || 0),
        'Income_from_Other_Sources': this.formatAmount(itrData.income?.otherIncome || 0),
        'Business_Income': this.formatAmount(itrData.income?.businessIncome || 0),
        'Capital_Gains': this.formatAmount(itrData.income?.capitalGains || 0),
        'Total_Gross_Income': 0 // Will be calculated
      },

      // Deductions
      'Deductions': {
        'Section_80C': this.formatAmount(itrData.deductions?.section80C || 0),
        'Section_80D': this.formatAmount(itrData.deductions?.section80D || 0),
        'Section_80E': this.formatAmount(itrData.deductions?.section80E || 0),
        'Section_80G': this.formatAmount(itrData.deductions?.section80G || 0),
        'Section_80TTA': this.formatAmount(itrData.deductions?.section80TTA || 0),
        'Total_Deductions': 0 // Will be calculated
      },

      // Tax calculation
      'Tax_Calculation': {
        'Total_Income': 0, // Will be calculated
        'Total_Tax_Liability': 0, // Will be calculated
        'Education_Cess': 0, // Will be calculated
        'Total_Tax_Payable': 0, // Will be calculated
        'TDS_TCS': this.formatAmount(itrData.tds?.totalTDS || 0),
        'Advance_Tax': this.formatAmount(itrData.taxes?.advanceTax || 0),
        'Self_Assessment_Tax': this.formatAmount(itrData.taxes?.selfAssessmentTax || 0),
        'Total_Tax_Paid': 0 // Will be calculated
      },

      // Verification
      'Verification': {
        'Declaration': 'I declare that the information furnished above is true to the best of my knowledge and belief.',
        'Place': itrData.verification?.place || user.address?.city || '',
        'Date': currentDate.split('T')[0],
        'Signature_Type': itrData.verification?.signatureType || 'ELECTRONIC'
      }
    };

    // Calculate derived values
    this.calculateDerivedValues(baseJson);

    // Add ITR type specific fields
    this.addITRTypeSpecificFields(baseJson, itrData, itrType);

    return baseJson;
  }

  /**
   * Generate client-side JSON for immediate download
   */
  generateClientJson(itrData, itrType, assessmentYear, user) {
    const currentDate = new Date().toISOString();

    return {
      // Metadata
      'metadata': {
        'itrType': itrType,
        'assessmentYear': assessmentYear,
        'generatedAt': currentDate,
        'generatedBy': 'BurnBlack ITR Platform',
        'version': '1.0',
        'purpose': 'TAX_FILING',
        'format': 'GOVT_COMPLIANT'
      },

      // Taxpayer information
      'taxpayer': {
        'pan': itrData.personal?.pan || user.pan || '',
        'name': `${itrData.personal?.firstName || user.firstName || ''} ${itrData.personal?.lastName || user.lastName || ''}`,
        'email': itrData.personal?.email || user.email || '',
        'phone': itrData.personal?.phone || user.phone || '',
        'address': itrData.personal?.address || user.address || {}
      },

      // Complete form data
      'formData': itrData,

      // Calculations
      'calculations': {
        'grossIncome': this.calculateGrossIncome(itrData),
        'totalDeductions': this.calculateTotalDeductions(itrData),
        'taxableIncome': this.calculateTaxableIncome(itrData),
        'totalTax': this.calculateTotalTax(itrData)
      },

      // Download information
      'downloadInfo': {
        'fileName': this.generateFileName(itrType, assessmentYear),
        'instructions': [
          '1. Download this JSON file',
          '2. Visit Income Tax Department e-filing portal',
          '3. Go to "Upload Return" section',
          '4. Select "Upload JSON" option',
          '5. Upload this JSON file',
          '6. Verify the data and submit',
          '7. Download acknowledgement'
        ]
      }
    };
  }

  /**
   * Calculate derived financial values
   */
  calculateDerivedValues(jsonData) {
    const incomeDetails = jsonData.Income_Details;
    const deductions = jsonData.Deductions;

    // Calculate total gross income
    incomeDetails.Total_Gross_Income = this.formatAmount(
      parseFloat(incomeDetails.Income_from_Salary || 0) +
      parseFloat(incomeDetails.Income_from_House_Property || 0) +
      parseFloat(incomeDetails.Income_from_Other_Sources || 0) +
      parseFloat(incomeDetails.Business_Income || 0) +
      parseFloat(incomeDetails.Capital_Gains || 0)
    );

    // Calculate total deductions
    deductions.Total_Deductions = this.formatAmount(
      parseFloat(deductions.Section_80C || 0) +
      parseFloat(deductions.Section_80D || 0) +
      parseFloat(deductions.Section_80E || 0) +
      parseFloat(deductions.Section_80G || 0) +
      parseFloat(deductions.Section_80TTA || 0)
    );

    // Calculate taxable income
    const taxableIncome = parseFloat(incomeDetails.Total_Gross_Income) - parseFloat(deductions.Total_Deductions);

    // Calculate tax (simplified calculation - actual tax slabs would be more complex)
    let taxLiability = 0;
    if (taxableIncome > 0) {
      if (taxableIncome <= 250000) {
        taxLiability = 0;
      } else if (taxableIncome <= 500000) {
        taxLiability = (taxableIncome - 250000) * 0.05;
      } else if (taxableIncome <= 1000000) {
        taxLiability = 12500 + (taxableIncome - 500000) * 0.2;
      } else {
        taxLiability = 112500 + (taxableIncome - 1000000) * 0.3;
      }
    }

    jsonData.Tax_Calculation.Total_Income = this.formatAmount(taxableIncome);
    jsonData.Tax_Calculation.Total_Tax_Liability = this.formatAmount(taxLiability);
    jsonData.Tax_Calculation.Education_Cess = this.formatAmount(taxLiability * 0.04); // 4% education cess
    jsonData.Tax_Calculation.Total_Tax_Payable = this.formatAmount(
      parseFloat(jsonData.Tax_Calculation.Total_Tax_Liability) +
      parseFloat(jsonData.Tax_Calculation.Education_Cess)
    );

    // Calculate total tax paid
    jsonData.Tax_Calculation.Total_Tax_Paid = this.formatAmount(
      parseFloat(jsonData.Tax_Calculation.TDS_TCS) +
      parseFloat(jsonData.Tax_Calculation.Advance_Tax) +
      parseFloat(jsonData.Tax_Calculation.Self_Assessment_Tax)
    );
  }

  /**
   * Add ITR type specific fields
   */
  addITRTypeSpecificFields(jsonData, itrData, itrType) {
    switch (itrType) {
      case 'ITR-1':
        // ITR-1 specific fields
        jsonData.ITR1_Specific = {
          'Income_from_Salary_Detailed': itrData.salaryDetails || {},
          'Income_from_House_Property_Detailed': itrData.housePropertyDetails || {},
          'Business_Income_Already_Covered': 'NO',
          'Capital_Gains_Already_Covered': 'NO'
        };
        break;

      case 'ITR-2':
        // ITR-2 specific fields (for capital gains)
        jsonData.ITR2_Specific = {
          'Capital_Gains_Detailed': itrData.capitalGainsDetails || {},
          'Foreign_Income_Details': itrData.foreignIncomeDetails || {}
        };
        break;

      case 'ITR-3':
        // ITR-3 specific fields (for business income)
        jsonData.ITR3_Specific = {
          'Business_Profit_Loss': itrData.businessDetails || {},
          'Balance_Sheet_Details': itrData.balanceSheet || {}
        };
        break;

      case 'ITR-4':
        // ITR-4 specific fields (presumptive income)
        jsonData.ITR4_Specific = {
          'Presumptive_Income_Details': itrData.presumptiveIncome || {},
          'Business_Turnover': itrData.businessTurnover || {}
        };
        break;
    }
  }

  /**
   * Helper methods for calculations
   */
  calculateGrossIncome(itrData) {
    return this.formatAmount(
      parseFloat(itrData.income?.salaryIncome || 0) +
      parseFloat(itrData.income?.housePropertyIncome || 0) +
      parseFloat(itrData.income?.otherIncome || 0) +
      parseFloat(itrData.income?.businessIncome || 0) +
      parseFloat(itrData.income?.capitalGains || 0)
    );
  }

  calculateTotalDeductions(itrData) {
    return this.formatAmount(
      parseFloat(itrData.deductions?.section80C || 0) +
      parseFloat(itrData.deductions?.section80D || 0) +
      parseFloat(itrData.deductions?.section80E || 0) +
      parseFloat(itrData.deductions?.section80G || 0)
    );
  }

  calculateTaxableIncome(itrData) {
    const grossIncome = parseFloat(this.calculateGrossIncome(itrData));
    const totalDeductions = parseFloat(this.calculateTotalDeductions(itrData));
    return this.formatAmount(Math.max(0, grossIncome - totalDeductions));
  }

  calculateTotalTax(itrData) {
    const taxableIncome = parseFloat(this.calculateTaxableIncome(itrData));
    let tax = 0;

    if (taxableIncome <= 250000) {
      tax = 0;
    } else if (taxableIncome <= 500000) {
      tax = (taxableIncome - 250000) * 0.05;
    } else if (taxableIncome <= 1000000) {
      tax = 12500 + (taxableIncome - 500000) * 0.2;
    } else {
      tax = 112500 + (taxableIncome - 1000000) * 0.3;
    }

    return this.formatAmount(tax + (tax * 0.04)); // Include 4% education cess
  }

  /**
   * Format amount as per government requirements
   */
  formatAmount(amount) {
    return parseFloat(amount || 0).toFixed(2);
  }

  /**
   * Generate filename for download
   */
  generateFileName(itrType, assessmentYear) {
    const currentDate = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    return `${itrType}_${assessmentYear}_${currentDate}.json`;
  }

  /**
   * Generate checksum for integrity verification
   */
  generateChecksum(data) {
    // Simple hash function for checksum (in production, use SHA-256)
    const str = JSON.stringify(data);
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      const char = str.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32-bit integer
    }
    return Math.abs(hash).toString(16);
  }

  /**
   * Download JSON file directly in browser
   */
  downloadJsonFile(jsonData, fileName) {
    const jsonString = JSON.stringify(jsonData, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    link.style.display = 'none';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  }

  /**
   * Validate JSON before export
   */
  validateJsonForExport(itrData, itrType) {
    const requiredFields = {
      personal: ['firstName', 'lastName', 'pan', 'email'],
      income: ['salaryIncome'],
      verification: ['place']
    };

    for (const [section, fields] of Object.entries(requiredFields)) {
      if (!itrData[section]) {
        throw new Error(`Missing required section: ${section}`);
      }

      for (const field of fields) {
        if (!itrData[section][field]) {
          throw new Error(`Missing required field: ${section}.${field}`);
        }
      }
    }

    return true;
  }
}

export const itrJsonExportService = new ITRJsonExportService();
export default itrJsonExportService;